name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spm:
    name: SPM Build
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS_13']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Select Xcode Version (11.3.1)
        run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app/Contents/Developer
      - name: Build
        run: Scripts/build.swift spm ${{ matrix.platform }}
